### ISSUE TITLE
Ground Control on OpenELEC?

### ISSUE THREAD

**Issue by redraw** [jondot/groundcontrol#32]
Is it possible to install Ground Control on OpenELEC?
After reading your installation readme, I realize there's no /etc/init.d folder in openelec.

**Comment by jondot** [comment]
Hi, I believe there should be some kind of init mechanism, Groundcontrol is a simple binary and doesn't require anything else as prerequisite, so you can use any init mechanism you wish.

On OpenELEC, check this out http://wiki.openelec.tv/index.php?title=Autostart.sh

**Comment by traful** [comment]
thanks!

**Comment by redraw** [comment]
thanks!
